baseURL = 'https://www.hbdfab.com/' # Updated to your new custom domain
languageCode = 'en-us'
title = 'Harley Bondini' # Changed from the long sentence to your Name/Brand
theme = 'hb-theme'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This allows us to embed the 3D Model Viewer later

[menu]
  [[menu.main]]
    name = 'Portfolio'
    url = '/projects/'
    weight = 2
  [[menu.main]]
    name = 'Instagram'
    url = 'https://www.instagram.com/hb_dfab'
    weight = 3
    [menu.main.params]
      icon = 'instagram'
